image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - npm install
          - pipe: snyk/snyk-scan:0.5.1  #using snyk plugin
            variables:
              SNYK_TOKEN: "$SNYK_TOKEN"
              LANGUAGE: "npm"   # Required unless SNYK_TEST_JSON_INPUT is set
              DONT_BREAK_BUILD: "true" # Optional.
              MONITOR: "false"  # Optional.
              # SEVERITY_THRESHOLD: "<low|medium|high|critical>" # Optional.
              # ORGANIZATION: "<string>" # Optional.
              # PROJECT_FOLDER: "<string>" # Optional.
              # TARGET_FILE: "<string>" # Optional.
              # EXTRA_ARGS: "<string>" # Optional.
              # DEBUG: "<boolean>" # Optional.
    - step:
        script:
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build -t jmiles6620/juice-shop .
          - docker push jmiles6620/juice-shop
        services:
          - docker

